version: "3.8"

services:
  mongodb:
    image: mongo
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=user
    #   - MONGO_INITDB_ROOT_PASSWORD=pass
    ports: 
        - 27017:27017
    # volumes:
    #   - type: bind
    #     source: ./data
    #     target: /data/db